
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author alunolages
 */
public class CadastroDeProdutosPainel extends javax.swing.JPanel {
    
    DefaultListModel model = new DefaultListModel();
    ArrayList<Produtos> produtosArray = new ArrayList<>();
    //private ArrayList<Usuario> usuarioArray;
    /**
     * Creates new form CadastroDeProdutosPainel
     */
    public CadastroDeProdutosPainel() {
        initComponents();
        //jCB_itensCadastrados.removeAllItems();
        PainelSupermercado supermercado = new PainelSupermercado(produtosArray);
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jTF_digiteNome1.setVisible(false);
        jTF_digiteValor1.setVisible(false);
        jL_digiteNome1.setVisible(false);
        jL_diiteValor1.setVisible(false);
        jB_cadastrar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_titulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jL_itensCadastrados3 = new javax.swing.JLabel();
        jB_voltarLogin = new javax.swing.JButton();
        jB_cadastrarProduto = new javax.swing.JButton();
        jB_editarProduto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jL_itensCadastrados1 = new javax.swing.JLabel();
        jL_digiteNome = new javax.swing.JLabel();
        jTF_digiteNome = new javax.swing.JTextField();
        jL_diiteValor = new javax.swing.JLabel();
        jTF_digiteValor = new javax.swing.JTextField();
        jB_limpar = new javax.swing.JButton();
        jB_cadastrar = new javax.swing.JButton();
        jB_voltarLogin2 = new javax.swing.JButton();
        jB_voltarOpcoes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jL_itensCadastrados = new javax.swing.JLabel();
        jCB_itensCadastrados = new javax.swing.JComboBox<>();
        jB_excluirIten = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jL_itensCadastrados2 = new javax.swing.JLabel();
        jL_valorItensCadastrados = new javax.swing.JLabel();
        jB_voltarLogin3 = new javax.swing.JButton();
        jB_voltarOpcoes1 = new javax.swing.JButton();
        jL_digiteNome1 = new javax.swing.JLabel();
        jL_diiteValor1 = new javax.swing.JLabel();
        jTF_digiteValor1 = new javax.swing.JTextField();
        jTF_digiteNome1 = new javax.swing.JTextField();
        jB_cadastrar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(84, 180, 53));

        jL_titulo2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jL_titulo2.setForeground(new java.awt.Color(240, 255, 66));
        jL_titulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo25.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(84, 180, 53));

        jL_itensCadastrados3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_itensCadastrados3.setForeground(new java.awt.Color(240, 255, 66));
        jL_itensCadastrados3.setText("Escolha alguma das opcções:");

        jB_voltarLogin.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltarLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltarLogin.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltarLogin.setText("Voltar ao login");
        jB_voltarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_voltarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarLoginMouseClicked(evt);
            }
        });
        jB_voltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarLoginActionPerformed(evt);
            }
        });

        jB_cadastrarProduto.setBackground(new java.awt.Color(33, 180, 53));
        jB_cadastrarProduto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_cadastrarProduto.setForeground(new java.awt.Color(240, 255, 66));
        jB_cadastrarProduto.setText("Cadastrar produto");
        jB_cadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_cadastrarProdutoMouseClicked(evt);
            }
        });
        jB_cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarProdutoActionPerformed(evt);
            }
        });

        jB_editarProduto.setBackground(new java.awt.Color(33, 180, 53));
        jB_editarProduto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_editarProduto.setForeground(new java.awt.Color(240, 255, 66));
        jB_editarProduto.setText("Editar produto");
        jB_editarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_editarProdutoMouseClicked(evt);
            }
        });
        jB_editarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_itensCadastrados3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_cadastrarProduto)
                                .addGap(18, 18, 18)
                                .addComponent(jB_editarProduto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jB_voltarLogin)
                                .addGap(67, 67, 67)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_itensCadastrados3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_cadastrarProduto)
                    .addComponent(jB_editarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jB_voltarLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(84, 180, 53));
        jPanel2.setPreferredSize(new java.awt.Dimension(405, 145));

        jL_itensCadastrados1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_itensCadastrados1.setForeground(new java.awt.Color(240, 255, 66));
        jL_itensCadastrados1.setText("Cadastro de produtos:");

        jL_digiteNome.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_digiteNome.setForeground(new java.awt.Color(240, 255, 66));
        jL_digiteNome.setText("Digite o nome:");

        jTF_digiteNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_digiteNomeKeyPressed(evt);
            }
        });

        jL_diiteValor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_diiteValor.setForeground(new java.awt.Color(240, 255, 66));
        jL_diiteValor.setText("Digite o valor:");

        jTF_digiteValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_digiteValorKeyPressed(evt);
            }
        });

        jB_limpar.setBackground(new java.awt.Color(33, 180, 53));
        jB_limpar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_limpar.setForeground(new java.awt.Color(240, 255, 66));
        jB_limpar.setText("Limpar");
        jB_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_limparMouseClicked(evt);
            }
        });
        jB_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limparActionPerformed(evt);
            }
        });

        jB_cadastrar.setBackground(new java.awt.Color(33, 180, 53));
        jB_cadastrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_cadastrar.setForeground(new java.awt.Color(240, 255, 66));
        jB_cadastrar.setText("Cadastrar");
        jB_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_cadastrarMouseClicked(evt);
            }
        });
        jB_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarActionPerformed(evt);
            }
        });

        jB_voltarLogin2.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltarLogin2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltarLogin2.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltarLogin2.setText("Voltar ao login");
        jB_voltarLogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_voltarLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarLogin2MouseClicked(evt);
            }
        });
        jB_voltarLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarLogin2ActionPerformed(evt);
            }
        });

        jB_voltarOpcoes.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltarOpcoes.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltarOpcoes.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltarOpcoes.setText("Voltar as opções");
        jB_voltarOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_voltarOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarOpcoesMouseClicked(evt);
            }
        });
        jB_voltarOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jL_itensCadastrados1)
                        .addGap(277, 277, 277))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jL_diiteValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_digiteValor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jL_digiteNome)
                                .addGap(5, 5, 5)
                                .addComponent(jTF_digiteNome))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jB_voltarOpcoes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_voltarLogin2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jB_limpar)
                                        .addGap(37, 37, 37)
                                        .addComponent(jB_cadastrar)
                                        .addGap(12, 12, 12)))))
                        .addGap(42, 42, 42))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jL_itensCadastrados1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_digiteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_digiteNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_diiteValor)
                    .addComponent(jTF_digiteValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_cadastrar)
                    .addComponent(jB_limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_voltarOpcoes)
                    .addComponent(jB_voltarLogin2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(84, 180, 53));

        jL_itensCadastrados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_itensCadastrados.setForeground(new java.awt.Color(240, 255, 66));
        jL_itensCadastrados.setText("Itens cadastrados:");

        jCB_itensCadastrados.setBackground(new java.awt.Color(84, 180, 53));
        jCB_itensCadastrados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCB_itensCadastrados.setForeground(new java.awt.Color(0, 204, 0));
        jCB_itensCadastrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCB_itensCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_itensCadastradosActionPerformed(evt);
            }
        });

        jB_excluirIten.setBackground(new java.awt.Color(33, 180, 53));
        jB_excluirIten.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_excluirIten.setForeground(new java.awt.Color(240, 255, 66));
        jB_excluirIten.setText("Excluir item");
        jB_excluirIten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_excluirIten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_excluirItenMouseClicked(evt);
            }
        });
        jB_excluirIten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluirItenActionPerformed(evt);
            }
        });

        jB_editar.setBackground(new java.awt.Color(33, 180, 53));
        jB_editar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_editar.setForeground(new java.awt.Color(240, 255, 66));
        jB_editar.setText("Editar item");
        jB_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_editarMouseClicked(evt);
            }
        });
        jB_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarActionPerformed(evt);
            }
        });

        jL_itensCadastrados2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_itensCadastrados2.setForeground(new java.awt.Color(240, 255, 66));
        jL_itensCadastrados2.setText("<html>Valor do produto <br>selecionado:<html>");

        jL_valorItensCadastrados.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jL_valorItensCadastrados.setForeground(new java.awt.Color(240, 255, 66));
        jL_valorItensCadastrados.setText("R$");

        jB_voltarLogin3.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltarLogin3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltarLogin3.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltarLogin3.setText("Voltar ao login");
        jB_voltarLogin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_voltarLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarLogin3Login3MouseClicked(evt);
            }
        });
        jB_voltarLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarLogin3Login3ActionPerformed(evt);
            }
        });

        jB_voltarOpcoes1.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltarOpcoes1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltarOpcoes1.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltarOpcoes1.setText("Voltar as opções");
        jB_voltarOpcoes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_voltarOpcoes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarOpcoes1MouseClicked(evt);
            }
        });
        jB_voltarOpcoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarOpcoes1ActionPerformed(evt);
            }
        });

        jL_digiteNome1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_digiteNome1.setForeground(new java.awt.Color(240, 255, 66));
        jL_digiteNome1.setText("Digite o nome:");

        jL_diiteValor1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_diiteValor1.setForeground(new java.awt.Color(240, 255, 66));
        jL_diiteValor1.setText("Digite o valor:");

        jTF_digiteValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_digiteValor1KeyPressed(evt);
            }
        });

        jTF_digiteNome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_digiteNome1KeyPressed(evt);
            }
        });

        jB_cadastrar1.setBackground(new java.awt.Color(33, 180, 53));
        jB_cadastrar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_cadastrar1.setForeground(new java.awt.Color(240, 255, 66));
        jB_cadastrar1.setText("Cadastrar");
        jB_cadastrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_cadastrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_itensCadastrados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCB_itensCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_voltarOpcoes1))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jB_excluirIten)
                                    .addComponent(jB_editar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_valorItensCadastrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_itensCadastrados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(jB_voltarLogin3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_diiteValor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_digiteValor1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_digiteNome1)
                                .addGap(5, 5, 5)
                                .addComponent(jTF_digiteNome1)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_digiteNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_digiteNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_diiteValor1)
                    .addComponent(jTF_digiteValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jL_itensCadastrados)
                            .addGap(13, 13, 13))
                        .addComponent(jL_itensCadastrados2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB_cadastrar1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_itensCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_valorItensCadastrados)
                    .addComponent(jB_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_excluirIten)
                    .addComponent(jB_voltarLogin3)
                    .addComponent(jB_voltarOpcoes1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jL_titulo2)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_excluirItenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_excluirItenMouseClicked
        /*Object[] options = {"sim", "não", "cancelar"};
        if (JOptionPane.showOptionDialog(null, "Tem certeza?", "Remover", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) ==0) {
            JFramePrincipal.supermercado.getProdutos().remove(jCB_itensCadastrados.getSelectedIndex());
            jCB_itensCadastrados.removeItem(jCB_itensCadastrados.getSelectedItem());
        }*/
        Object[] options = {"sim", "cancelar"};
        if (JOptionPane.showOptionDialog(null, "Tem certeza?", "Remover", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) ==0) {
            /*jCB_carrinho.removeItem(jCB_carrinho.getSelectedItem());
            JFramePrincipal.carrinho.getCarrinho().remove(JFramePrincipal.carrinho.getCarrinho().get(jCB_carrinho.getSelectedIndex()));*/
            if (!JFramePrincipal.supermercado.getProdutos().isEmpty() && jCB_itensCadastrados.getSelectedIndex() > -1) {
                System.out.println(jCB_itensCadastrados.getSelectedIndex());
                
                Object index =jCB_itensCadastrados.getSelectedItem();
                
                JFramePrincipal.supermercado.getProdutos().remove(jCB_itensCadastrados.getSelectedIndex());
                jCB_itensCadastrados.removeItem(index);
                
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum item foi selecionado ou não ha oque excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        
            
        }
    }//GEN-LAST:event_jB_excluirItenMouseClicked

    private void jB_excluirItenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluirItenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_excluirItenActionPerformed

    private void jCB_itensCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_itensCadastradosActionPerformed
        // TODO add your handling code here:produtosArray
        
        if (!JFramePrincipal.supermercado.getProdutos().isEmpty() && jCB_itensCadastrados.getSelectedIndex() > -1) {
        //Mostra o valor do item selecionado:
        String v = JFramePrincipal.supermercado.getProdutos().get(jCB_itensCadastrados.getSelectedIndex()).getValorProduto();

        Double valor = Double.parseDouble(v);
        jL_valorItensCadastrados.setText("R$"+valor);
        }else{
            jL_valorItensCadastrados.setText("R$");
        }
    }//GEN-LAST:event_jCB_itensCadastradosActionPerformed

    private void jB_voltarLogin3Login3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarLogin3Login3MouseClicked
        JFramePrincipal.painel1 = new Login();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(JFramePrincipal.painel2);
        janela.add(JFramePrincipal.painel1, BorderLayout.CENTER);
        janela.pack();
         
    }//GEN-LAST:event_jB_voltarLogin3Login3MouseClicked

    private void jB_voltarLogin3Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarLogin3Login3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltarLogin3Login3ActionPerformed

    private void jB_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_editarMouseClicked
        if (!JFramePrincipal.supermercado.getProdutos().isEmpty() && jCB_itensCadastrados.getSelectedIndex() > -1) {
            String produtoSelecionado = jCB_itensCadastrados.getSelectedItem().toString();
            jTF_digiteNome1.setVisible(true);
            jTF_digiteValor1.setVisible(true);
            jL_digiteNome1.setVisible(true);
            jL_diiteValor1.setVisible(true);
            jB_cadastrar1.setVisible(true);
            //Obtem os valores dos produtos que será editado
            for(Produtos produtos : JFramePrincipal.supermercado.getProdutos()){
                if(produtos.getNomeProduto().equals(produtoSelecionado)){
                    jTF_digiteNome1.setText(produtos.getNomeProduto());
                    jTF_digiteValor1.setText(String.valueOf(produtos.getValorProduto()));
                    jCB_itensCadastrados.removeItem(jCB_itensCadastrados.getSelectedItem());
                    JFramePrincipal.supermercado.getProdutos().remove(produtos);
                    break;
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum item foi selecionado ou não ha oque editar!");
        }
    }//GEN-LAST:event_jB_editarMouseClicked

    private void jB_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_editarActionPerformed

    private void jB_voltarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarLoginMouseClicked
        JFramePrincipal.painel1 = new Login();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(JFramePrincipal.painel2);
        janela.add(JFramePrincipal.painel1, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jB_voltarLoginMouseClicked

    private void jB_voltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltarLoginActionPerformed

    private void jB_cadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_cadastrarProdutoMouseClicked
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jB_cadastrarProdutoMouseClicked

    private void jB_cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_cadastrarProdutoActionPerformed

    private void jB_editarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_editarProdutoMouseClicked
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jB_editarProdutoMouseClicked

    private void jB_editarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_editarProdutoActionPerformed

    private void jB_voltarLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltarLogin2ActionPerformed

    private void jB_voltarLogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarLogin2MouseClicked
        JFramePrincipal.painel1 = new Login();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(JFramePrincipal.painel2);
        janela.add(JFramePrincipal.painel1, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jB_voltarLogin2MouseClicked

    private void jB_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_cadastrarActionPerformed

    private void jB_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_cadastrarMouseClicked
        try {
            long valor = Long.parseLong(jTF_digiteValor.getText());
            if (jTF_digiteNome.getText().equals("") || jTF_digiteValor.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }else {

                Produtos produtos = new Produtos(jTF_digiteNome.getText(), jTF_digiteValor.getText());
                //JFramePrincipal.supermercado.getProdutos().add(produtos);
                JFramePrincipal.supermercado.getProdutos().add(produtos);
                //

                //Array produtos, adicionando o nome jCB:
                /*String ultimoElemento = produtosArray.get(produtosArray.size()-1).getNomeProduto();
                jCB_itensCadastrados.addItem(ultimoElemento);*/
                String ultimoElemento = JFramePrincipal.supermercado.getProdutos().get(JFramePrincipal.supermercado.getProdutos().size()-1).getNomeProduto();
                jCB_itensCadastrados.addItem(ultimoElemento);
                //ImageIcon icon = new ImageIcon("src/Imagens/Logo25_greenMenor.png");
                JOptionPane.showMessageDialog(null,"O produto foi cadastrado!", "Supermercado Super", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos corretamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        jTF_digiteNome.setText("");
        jTF_digiteValor.setText("");
    }//GEN-LAST:event_jB_cadastrarMouseClicked

    private void jB_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_limparActionPerformed

    private void jB_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_limparMouseClicked
        jTF_digiteNome.setText("");
        jTF_digiteValor.setText("");
    }//GEN-LAST:event_jB_limparMouseClicked

    private void jTF_digiteNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_digiteNomeKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jTF_digiteValor.requestFocus();
        }
    }//GEN-LAST:event_jTF_digiteNomeKeyPressed

    private void jB_voltarOpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarOpcoesMouseClicked
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jB_voltarOpcoesMouseClicked

    private void jB_voltarOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltarOpcoesActionPerformed

    private void jB_voltarOpcoes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarOpcoes1MouseClicked
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jB_voltarOpcoes1MouseClicked

    private void jB_voltarOpcoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarOpcoes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltarOpcoes1ActionPerformed

    private void jTF_digiteNome1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_digiteNome1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jTF_digiteValor1.requestFocus();
        }
    }//GEN-LAST:event_jTF_digiteNome1KeyPressed

    private void jB_cadastrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_cadastrar1MouseClicked
        try {
            long valor = Long.parseLong(jTF_digiteValor1.getText());
            if (jTF_digiteNome1.getText().equals("") || jTF_digiteValor1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }else {

                Produtos produtos = new Produtos(jTF_digiteNome1.getText(), jTF_digiteValor1.getText());
                //JFramePrincipal.supermercado.getProdutos().add(produtos);
                JFramePrincipal.supermercado.getProdutos().add(produtos);
                //

                //Array produtos, adicionando o nome jCB:
                /*String ultimoElemento = produtosArray.get(produtosArray.size()-1).getNomeProduto();
                jCB_itensCadastrados.addItem(ultimoElemento);*/
                String ultimoElemento = JFramePrincipal.supermercado.getProdutos().get(JFramePrincipal.supermercado.getProdutos().size()-1).getNomeProduto();
                jCB_itensCadastrados.addItem(ultimoElemento);
                //ImageIcon icon = new ImageIcon("src/Imagens/Logo25_greenMenor.png");
                JOptionPane.showMessageDialog(null,"O produto foi cadastrado!", "Supermercado Super", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos corretamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        jTF_digiteNome.setText("");
        jTF_digiteValor.setText("");
    }//GEN-LAST:event_jB_cadastrar1MouseClicked

    private void jTF_digiteValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_digiteValorKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jB_cadastrar.requestFocus();
            try {
                long valor = Long.parseLong(jTF_digiteValor.getText());
                if (jTF_digiteNome.getText().equals("") || jTF_digiteValor.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
                }else {

                    Produtos produtos = new Produtos(jTF_digiteNome.getText(), jTF_digiteValor.getText());
                    //JFramePrincipal.supermercado.getProdutos().add(produtos);
                    JFramePrincipal.supermercado.getProdutos().add(produtos);
                    //

                    //Array produtos, adicionando o nome jCB:
                    /*String ultimoElemento = produtosArray.get(produtosArray.size()-1).getNomeProduto();
                    jCB_itensCadastrados.addItem(ultimoElemento);*/
                    String ultimoElemento = JFramePrincipal.supermercado.getProdutos().get(JFramePrincipal.supermercado.getProdutos().size()-1).getNomeProduto();
                    jCB_itensCadastrados.addItem(ultimoElemento);
                    //ImageIcon icon = new ImageIcon("src/Imagens/Logo25_greenMenor.png");
                    JOptionPane.showMessageDialog(null,"O produto foi cadastrado!", "Supermercado Super", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos corretamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            jTF_digiteNome.setText("");
            jTF_digiteValor.setText("");
        }
    }//GEN-LAST:event_jTF_digiteValorKeyPressed

    private void jTF_digiteValor1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_digiteValor1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jB_cadastrar1.requestFocus();
            try {
                long valor = Long.parseLong(jTF_digiteValor1.getText());
                if (jTF_digiteNome1.getText().equals("") || jTF_digiteValor1.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
                }else {

                    Produtos produtos = new Produtos(jTF_digiteNome1.getText(), jTF_digiteValor1.getText());
                    //JFramePrincipal.supermercado.getProdutos().add(produtos);
                    JFramePrincipal.supermercado.getProdutos().add(produtos);
                    //

                    //Array produtos, adicionando o nome jCB:
                    /*String ultimoElemento = produtosArray.get(produtosArray.size()-1).getNomeProduto();
                    jCB_itensCadastrados.addItem(ultimoElemento);*/
                    String ultimoElemento = JFramePrincipal.supermercado.getProdutos().get(JFramePrincipal.supermercado.getProdutos().size()-1).getNomeProduto();
                    jCB_itensCadastrados.addItem(ultimoElemento);
                    //ImageIcon icon = new ImageIcon("src/Imagens/Logo25_greenMenor.png");
                    JOptionPane.showMessageDialog(null,"O produto foi cadastrado!", "Supermercado Super", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos corretamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            jTF_digiteNome1.setText("");
            jTF_digiteValor1.setText("");
        }
    }//GEN-LAST:event_jTF_digiteValor1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cadastrar;
    private javax.swing.JButton jB_cadastrar1;
    private javax.swing.JButton jB_cadastrarProduto;
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_editarProduto;
    private javax.swing.JButton jB_excluirIten;
    private javax.swing.JButton jB_limpar;
    private javax.swing.JButton jB_voltarLogin;
    private javax.swing.JButton jB_voltarLogin2;
    private javax.swing.JButton jB_voltarLogin3;
    private javax.swing.JButton jB_voltarOpcoes;
    private javax.swing.JButton jB_voltarOpcoes1;
    private javax.swing.JComboBox<String> jCB_itensCadastrados;
    private javax.swing.JLabel jL_digiteNome;
    private javax.swing.JLabel jL_digiteNome1;
    private javax.swing.JLabel jL_diiteValor;
    private javax.swing.JLabel jL_diiteValor1;
    private javax.swing.JLabel jL_itensCadastrados;
    private javax.swing.JLabel jL_itensCadastrados1;
    private javax.swing.JLabel jL_itensCadastrados2;
    private javax.swing.JLabel jL_itensCadastrados3;
    private javax.swing.JLabel jL_titulo2;
    private javax.swing.JLabel jL_valorItensCadastrados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTF_digiteNome;
    private javax.swing.JTextField jTF_digiteNome1;
    private javax.swing.JTextField jTF_digiteValor;
    private javax.swing.JTextField jTF_digiteValor1;
    // End of variables declaration//GEN-END:variables

    
}
