
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author alunolages
 */
public class Login extends javax.swing.JPanel {
    
    private ArrayList<Produtos> produtosArray;
    ArrayList<Usuario> usuarioArray = new ArrayList<>();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_login = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jL_CPF = new javax.swing.JLabel();
        jL_nome = new javax.swing.JLabel();
        jRB_administrador = new javax.swing.JRadioButton();
        jRB_cliente = new javax.swing.JRadioButton();
        jB_entrar = new javax.swing.JButton();
        jTF_CPF = new javax.swing.JTextField();
        jTF_nome = new javax.swing.JTextField();
        jL_titulo2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(84, 180, 53));

        jL_CPF.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_CPF.setForeground(new java.awt.Color(240, 255, 66));
        jL_CPF.setText("CPF:");

        jL_nome.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_nome.setForeground(new java.awt.Color(240, 255, 66));
        jL_nome.setText("Nome:");

        jRB_administrador.setBackground(new java.awt.Color(84, 180, 53));
        bG_login.add(jRB_administrador);
        jRB_administrador.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRB_administrador.setForeground(new java.awt.Color(240, 255, 66));
        jRB_administrador.setText("Administrador");
        jRB_administrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jRB_cliente.setBackground(new java.awt.Color(84, 180, 53));
        bG_login.add(jRB_cliente);
        jRB_cliente.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRB_cliente.setForeground(new java.awt.Color(240, 255, 66));
        jRB_cliente.setText("Cliente");
        jRB_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jB_entrar.setBackground(new java.awt.Color(33, 180, 53));
        jB_entrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_entrar.setForeground(new java.awt.Color(240, 255, 66));
        jB_entrar.setText("Entrar");
        jB_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_entrarMouseClicked(evt);
            }
        });
        jB_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_entrarActionPerformed(evt);
            }
        });

        jTF_CPF.setFont(new java.awt.Font("Segoe UI Variable", 0, 10)); // NOI18N
        jTF_CPF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTF_CPF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_CPFKeyPressed(evt);
            }
        });

        jTF_nome.setFont(new java.awt.Font("Segoe UI Variable", 0, 10)); // NOI18N
        jTF_nome.setDisabledTextColor(new java.awt.Color(255, 255, 0));
        jTF_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_nomeKeyPressed(evt);
            }
        });

        jL_titulo2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jL_titulo2.setForeground(new java.awt.Color(240, 255, 66));
        jL_titulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo25.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_nome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL_CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTF_CPF))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jRB_administrador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRB_cliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jB_entrar)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_titulo2)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jL_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_CPF)
                    .addComponent(jTF_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_nome)
                    .addComponent(jTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB_administrador)
                    .addComponent(jRB_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_entrar)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_entrarMouseClicked
        try {
            long cpfV = Long.parseLong(jTF_CPF.getText());
        if (jTF_CPF.getText().equals("") || jTF_nome.getText().equals("") || bG_login.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else {
            ImageIcon icon = new ImageIcon("src/Imagens/Logo25_greenMenor.png");
            JOptionPane.showMessageDialog(null,"<html>Sejá bem vindo "+jTF_nome.getText()+"!<br> Precione o OK para<br> continuar!<html>", "Supermercado Super", JOptionPane.INFORMATION_MESSAGE, icon);
            //
            Usuario usuario = new Usuario(jTF_CPF.getText(), jTF_nome.getText());
            usuarioArray.add(usuario);
            //
            
            Usuario usuario1 = new Usuario(jTF_CPF.getText(), jTF_nome.getText());
            String jRBSelecionado = "não selecionado";
            if (jRB_administrador.isSelected()) {
                jRBSelecionado = "administrador";
                JFramePrincipal.painel2 = new CadastroDeProdutosPainel();
                JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
                janela.getContentPane().remove(JFramePrincipal.painel1);
                janela.add(JFramePrincipal.painel2, BorderLayout.CENTER);
                janela.pack();
            } else if (jRB_cliente.isSelected()) {
                jRBSelecionado = "cliente";
                JFramePrincipal.painel3 = new PainelSupermercado(produtosArray);
                JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
                janela.getContentPane().remove(JFramePrincipal.painel1);
                janela.add(JFramePrincipal.painel3, BorderLayout.CENTER);
                janela.pack();
            }

            jTF_CPF.setText("");
            jTF_nome.setText("");
            
            
            //JFramePrincipal.user.getUsuario().add(usuario1);*/
            }
        }catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos corretamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jB_entrarMouseClicked

    private void jB_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_entrarActionPerformed
        
    }//GEN-LAST:event_jB_entrarActionPerformed

    private void jTF_CPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_CPFKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jTF_nome.requestFocus();
        }
    }//GEN-LAST:event_jTF_CPFKeyPressed

    private void jTF_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_nomeKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jRB_cliente.requestFocus();
            
        }
    }//GEN-LAST:event_jTF_nomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG_login;
    private javax.swing.JButton jB_entrar;
    private javax.swing.JLabel jL_CPF;
    private javax.swing.JLabel jL_nome;
    private javax.swing.JLabel jL_titulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB_administrador;
    private javax.swing.JRadioButton jRB_cliente;
    private javax.swing.JTextField jTF_CPF;
    private javax.swing.JTextField jTF_nome;
    // End of variables declaration//GEN-END:variables
}
