

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author nicka
 */
public class PainelSupermercado extends javax.swing.JPanel {
    
    //DefaultListModel modelo = new DefaultListModel();
    //ArrayList<Produtos> produtosArray = new ArrayList<Produtos>();
    /**
     * Creates new form Supermercado
     */
    
    DefaultListModel model = new DefaultListModel();
    
    public PainelSupermercado(ArrayList<Produtos> produtosArray) {
        initComponents();
        JFramePrincipal.carrinho = new Carrinho();
        addProdutosCombo();
    }

    
    
    
    
    public void addProdutosCombo(){
        for(Produtos produtos : JFramePrincipal.supermercado.getProdutos()){
            jCB_produtos.addItem(produtos.getNomeProduto());
            /*model.addElement(produtos.getNomeProduto()); //jList
            jList_produtos.setModel(model);*/
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jL_titulo1 = new javax.swing.JLabel();
        jB_voltar = new javax.swing.JButton();
        jL_produtos = new javax.swing.JLabel();
        jLabel_carrinho = new javax.swing.JLabel();
        jB_adicionarCarrinho = new javax.swing.JButton();
        jB_removerCarrinho = new javax.swing.JButton();
        jL_totalPagar = new javax.swing.JLabel();
        jL_valorTotalPagar = new javax.swing.JLabel();
        jL_ProdutoSelecionado = new javax.swing.JLabel();
        jL_valorProdutoSelecionado = new javax.swing.JLabel();
        jB_imprimirNF = new javax.swing.JButton();
        jCB_produtos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_carrinho = new javax.swing.JList<>();
        jL_titulo3 = new javax.swing.JLabel();
        jB_voltar1 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jL_titulo1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jL_titulo1.setForeground(new java.awt.Color(240, 255, 66));
        jL_titulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo25.png"))); // NOI18N

        jB_voltar.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltar.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltar.setText("Voltar");
        jB_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarMouseClicked(evt);
            }
        });
        jB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(84, 180, 53));
        setMaximumSize(new java.awt.Dimension(421, 358));
        setPreferredSize(new java.awt.Dimension(421, 358));

        jL_produtos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_produtos.setForeground(new java.awt.Color(240, 255, 66));
        jL_produtos.setText("Produtos:");

        jLabel_carrinho.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel_carrinho.setForeground(new java.awt.Color(240, 255, 66));
        jLabel_carrinho.setText("Carrinho:");

        jB_adicionarCarrinho.setBackground(new java.awt.Color(33, 180, 53));
        jB_adicionarCarrinho.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_adicionarCarrinho.setForeground(new java.awt.Color(240, 255, 66));
        jB_adicionarCarrinho.setText("Adicionar ao carrinho");
        jB_adicionarCarrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_adicionarCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_adicionarCarrinhoMouseClicked(evt);
            }
        });
        jB_adicionarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_adicionarCarrinhoActionPerformed(evt);
            }
        });

        jB_removerCarrinho.setBackground(new java.awt.Color(33, 180, 53));
        jB_removerCarrinho.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_removerCarrinho.setForeground(new java.awt.Color(240, 255, 66));
        jB_removerCarrinho.setText("Remover do carrinho");
        jB_removerCarrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_removerCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_removerCarrinhoMouseClicked(evt);
            }
        });
        jB_removerCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_removerCarrinhoActionPerformed(evt);
            }
        });

        jL_totalPagar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_totalPagar.setForeground(new java.awt.Color(240, 255, 66));
        jL_totalPagar.setText("Total a pagar:");

        jL_valorTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jL_valorTotalPagar.setForeground(new java.awt.Color(240, 255, 66));
        jL_valorTotalPagar.setText("<valor>");

        jL_ProdutoSelecionado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jL_ProdutoSelecionado.setForeground(new java.awt.Color(240, 255, 66));
        jL_ProdutoSelecionado.setText("Valor do produto selecionado:");

        jL_valorProdutoSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jL_valorProdutoSelecionado.setForeground(new java.awt.Color(240, 255, 66));
        jL_valorProdutoSelecionado.setText("<valor>");

        jB_imprimirNF.setBackground(new java.awt.Color(33, 180, 53));
        jB_imprimirNF.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_imprimirNF.setForeground(new java.awt.Color(240, 255, 66));
        jB_imprimirNF.setText("ConcIuir a compra e imprimir a NF");
        jB_imprimirNF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_imprimirNF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_imprimirNFMouseClicked(evt);
            }
        });
        jB_imprimirNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_imprimirNFActionPerformed(evt);
            }
        });

        jCB_produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCB_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_produtosActionPerformed(evt);
            }
        });

        jList_carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jList_carrinho);

        jL_titulo3.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jL_titulo3.setForeground(new java.awt.Color(240, 255, 66));
        jL_titulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo25.png"))); // NOI18N

        jB_voltar1.setBackground(new java.awt.Color(33, 180, 53));
        jB_voltar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jB_voltar1.setForeground(new java.awt.Color(240, 255, 66));
        jB_voltar1.setText("Voltar");
        jB_voltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_voltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltar1MouseClicked(evt);
            }
        });
        jB_voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jL_produtos))
                                    .addComponent(jCB_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jB_removerCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_adicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_carrinho)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL_ProdutoSelecionado)
                                        .addGap(142, 142, 142)
                                        .addComponent(jL_totalPagar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jB_voltar1)
                                        .addGap(117, 117, 117)
                                        .addComponent(jB_imprimirNF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL_valorProdutoSelecionado)
                                        .addGap(257, 257, 257)
                                        .addComponent(jL_valorTotalPagar)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jL_titulo3)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jL_titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_produtos)
                        .addGap(12, 12, 12)
                        .addComponent(jCB_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jB_adicionarCarrinho)
                        .addGap(6, 6, 6)
                        .addComponent(jB_removerCarrinho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_carrinho)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_ProdutoSelecionado)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jL_totalPagar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_valorProdutoSelecionado)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jL_valorTotalPagar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_imprimirNF)
                    .addComponent(jB_voltar1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_removerCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_removerCarrinhoMouseClicked
        Object[] options = {"sim", "cancelar"};
        if (JOptionPane.showOptionDialog(null, "Tem certeza?", "Remover", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) ==0) {
            /*jCB_carrinho.removeItem(jCB_carrinho.getSelectedItem());
            JFramePrincipal.carrinho.getCarrinho().remove(JFramePrincipal.carrinho.getCarrinho().get(jCB_carrinho.getSelectedIndex()));*/
            if (!JFramePrincipal.carrinho.getCarrinho().isEmpty() && jList_carrinho.getSelectedIndex() > -1) {
                //jCB_carrinho.removeItem(jCB_carrinho.getSelectedItem());
                JFramePrincipal.carrinho.getCarrinho().remove(jList_carrinho.getSelectedIndex());
                //System.out.println(jList_carrinho.getSelectedIndex());
                model.remove(jList_carrinho.getSelectedIndex()); //jlist, retorna a posição do item selecionado.
                jList_carrinho.setModel(model);//jlist
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum item foi selecionado ou o carrinho está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
        //Pegar o valor total do carrinho:
        double somaValores = 0.0;
        int zero = 0;
        if(JFramePrincipal.carrinho.getCarrinho().isEmpty()){
            jL_valorTotalPagar.setText("R$"+ zero);
        }else{
            for(Produtos produtos : JFramePrincipal.carrinho.getCarrinho()){
                String valor = produtos.getValorProduto();
                somaValores = Double.parseDouble(valor);
            
            }
            jL_valorTotalPagar.setText("R$"+ somaValores);
        }
    }//GEN-LAST:event_jB_removerCarrinhoMouseClicked

    private void jB_adicionarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_adicionarCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_adicionarCarrinhoActionPerformed

    private void jB_adicionarCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_adicionarCarrinhoMouseClicked
         
        if (!JFramePrincipal.supermercado.getProdutos().isEmpty() && jCB_produtos.getSelectedIndex() > -1) {
            //jCB_carrinho.addItem(jCB_produtos.getSelectedItem().toString());
            model.addElement(jCB_produtos.getSelectedItem()); //jList
            jList_carrinho.setModel(model);
        
            JFramePrincipal.carrinho.getCarrinho().add(JFramePrincipal.supermercado.getProdutos().get(jCB_produtos.getSelectedIndex()));
            //JFramePrincipal.carrinho.getCarrinho().add(JFramePrincipal.supermercado.getProdutos().get(jList_produtos.getSelectedIndex()));
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum item foi selecionado ou não ha produtos para selecionar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        

        //Pegar o valor total do carrinho:
        double somaValores = 0.0;
        for(Produtos produtos : JFramePrincipal.carrinho.getCarrinho()){
            String valor = produtos.getValorProduto();
            somaValores += Double.parseDouble(valor);
        }
        jL_valorTotalPagar.setText("R$"+ somaValores);
         
    }//GEN-LAST:event_jB_adicionarCarrinhoMouseClicked

    private void jB_removerCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_removerCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_removerCarrinhoActionPerformed

    private void jB_imprimirNFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_imprimirNFMouseClicked
        if (!JFramePrincipal.carrinho.getCarrinho().isEmpty()){
            //Pegar o valor total do carrinho:
            double somaValores = 0.0;
            for(Produtos produtos : JFramePrincipal.carrinho.getCarrinho()){
                String valor = produtos.getValorProduto();
                somaValores += Double.parseDouble(valor);
            }
            
            ImageIcon icon = new ImageIcon("src/Imagens/Logo25_greenMenor.png");
            JOptionPane.showMessageDialog(null,"<html>"+JFramePrincipal.carrinho.getCarrinho() + "<br>Valor total da compra: R$" + somaValores+"<html>", "Nota Fiscal:", JOptionPane.INFORMATION_MESSAGE, icon);
        }else{
            JOptionPane.showMessageDialog(null, "Não ha nenhum produto no carrinho!!!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        

    }//GEN-LAST:event_jB_imprimirNFMouseClicked

    private void jB_imprimirNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_imprimirNFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_imprimirNFActionPerformed

    private void jCB_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_produtosActionPerformed
        //Ta pegando só o ultimo elemento nesse codigo://String v = JFramePrincipal.supermercado.getProdutos().get(JFramePrincipal.supermercado.getProdutos().size()-1).getValorProduto();
        //Mostra o valor do item selecionado:
        String v = JFramePrincipal.supermercado.getProdutos().get(jCB_produtos.getSelectedIndex()).getValorProduto();

        Double valor = Double.parseDouble(v);
        jL_valorProdutoSelecionado.setText("R$"+valor);
    }//GEN-LAST:event_jCB_produtosActionPerformed

    private void jB_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarMouseClicked
        JFramePrincipal.painel1 = new Login();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(JFramePrincipal.painel2);
        janela.add(JFramePrincipal.painel1, BorderLayout.CENTER);
        janela.pack();

    }//GEN-LAST:event_jB_voltarMouseClicked

    private void jB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltarActionPerformed

    private void jB_voltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltar1MouseClicked
        
        Object[] options = {"sim", "cancelar"};
        if (JOptionPane.showOptionDialog(null, "Tem certeza?", "Remover", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) ==0) {
            JFramePrincipal.painel1 = new Login();
            JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
            janela.getContentPane().remove(JFramePrincipal.painel3);
            janela.add(JFramePrincipal.painel1, BorderLayout.CENTER);
            janela.pack();
        }
    }//GEN-LAST:event_jB_voltar1MouseClicked

    private void jB_voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_voltar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_adicionarCarrinho;
    private javax.swing.JButton jB_imprimirNF;
    private javax.swing.JButton jB_removerCarrinho;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JButton jB_voltar1;
    private javax.swing.JComboBox<String> jCB_produtos;
    private javax.swing.JLabel jL_ProdutoSelecionado;
    private javax.swing.JLabel jL_produtos;
    private javax.swing.JLabel jL_titulo1;
    private javax.swing.JLabel jL_titulo3;
    private javax.swing.JLabel jL_totalPagar;
    private javax.swing.JLabel jL_valorProdutoSelecionado;
    private javax.swing.JLabel jL_valorTotalPagar;
    private javax.swing.JLabel jLabel_carrinho;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList_carrinho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
