
import Clases.Audios.AudioErro;
import Clases.MediaKmLitros2Classe;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author nicka
 */
public class PainelMediaKmsLitro2 extends javax.swing.JPanel {

    /**
     * Creates new form PainelMediaKmsLitro2
     */
    public PainelMediaKmsLitro2() {
        initComponents();
        MostrarDados();
    }
    
    public void MostrarDados(){
        for(MediaKmLitros2Classe mediaKmLitros2 : principalJFrame.usuario.getMediaKmsArray()){
            jTF_kilometragemInicial.setText(mediaKmLitros2.getKilometragemInicial());
            jTF_litrosAbastecidos1.setText(mediaKmLitros2.getLitrosAbastecidos());
            jTF_kilometragemFinal.setText(mediaKmLitros2.getKilometragemFinal());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tituloLogin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jL_kilometragemInicial = new javax.swing.JLabel();
        jTF_kilometragemInicial = new javax.swing.JTextField();
        jL_kilometragemFinal = new javax.swing.JLabel();
        jTF_kilometragemFinal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jB_calcular = new javax.swing.JButton();
        jB_limpar = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTF_litrosAbastecidos1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(179, 200, 144));

        jL_tituloLogin.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin.setText("Consult Trip");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jL_kilometragemInicial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jL_kilometragemInicial.setForeground(new java.awt.Color(255, 255, 255));
        jL_kilometragemInicial.setText("Kilometragem Inicial:");

        jL_kilometragemFinal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jL_kilometragemFinal.setForeground(new java.awt.Color(255, 255, 255));
        jL_kilometragemFinal.setText("Kilometragem final:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html> \nObs: Incira a kilometragem que seu veiculo estava quando você <br>abasteceu no campo \"Kilometragem incial\" e a quantidade de<br> litros que foram abastecidos no  campo \"Litros abastecidos\". <br>Posteriormente quando for abastecer novamente, insira a <br> kilometragem atual de seu veiculo no campo \"Kilometragem<br> final\", para assim obter o consumo médio.\n</html>");

        jB_calcular.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jB_calcular.setForeground(new java.awt.Color(109, 135, 116));
        jB_calcular.setText("Calcular");
        jB_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_calcularMouseClicked(evt);
            }
        });

        jB_limpar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_limpar.setForeground(new java.awt.Color(109, 135, 116));
        jB_limpar.setText("Limpar");
        jB_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_limparMouseClicked(evt);
            }
        });

        jB_voltar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_voltar.setForeground(new java.awt.Color(109, 135, 116));
        jB_voltar.setText("Voltar/Gravar dados");
        jB_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Litros abastecidos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_tituloLogin)
                .addGap(71, 189, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_kilometragemInicial)
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_kilometragemInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jL_kilometragemFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTF_kilometragemFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_litrosAbastecidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_voltar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jB_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_tituloLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_kilometragemInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_limpar)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTF_kilometragemInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_litrosAbastecidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_kilometragemFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_kilometragemFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB_voltar))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_calcularMouseClicked
        if (jTF_kilometragemInicial.getText().equals("") || jTF_litrosAbastecidos1.getText().equals("") || jTF_kilometragemFinal.getText().equals("")) {
            //Som de erro!
            AudioErro audioErro = new AudioErro();
            audioErro.AudioErro();
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else{
            float subtracao, media;
            subtracao = Float.parseFloat(jTF_kilometragemFinal.getText()) - Float.parseFloat(jTF_kilometragemInicial.getText());
            media = subtracao / Float.parseFloat(jTF_litrosAbastecidos1.getText());
            if (media == 1) {
                // Carregar a imagem desejada
                ImageIcon icon = new ImageIcon("src/Imagens/icons8-gasolina-50.png");
                // Exibir o JOptionPane com a imagem
                JOptionPane.showMessageDialog(null, "O seu veiculo está fazendo " + media + "Km por litro de combustível!", "Sua média de Km's por litro é:", JOptionPane.INFORMATION_MESSAGE, icon);
            }else {
                // Carregar a imagem desejada
                ImageIcon icon = new ImageIcon("src/Imagens/icons8-gasolina-50.png");
                // Exibir o JOptionPane com a imagem
                JOptionPane.showMessageDialog(null, "O seu veiculo está fazendo " + media + "Km's por litros de combustível!", "Sua média de Km's por litro é:", JOptionPane.INFORMATION_MESSAGE, icon);
            }
        }
        
    }//GEN-LAST:event_jB_calcularMouseClicked

    private void jB_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_limparMouseClicked
        jTF_kilometragemInicial.setText("");
        jTF_kilometragemFinal.setText("");
    }//GEN-LAST:event_jB_limparMouseClicked

    private void jB_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarMouseClicked
        principalJFrame.painel3 = new PainelCliente();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(principalJFrame.painel5);
        janela.add(principalJFrame.painel3, BorderLayout.CENTER);
        janela.pack();
        
        ArrayList<MediaKmLitros2Classe> dadosMediaKmArray = new ArrayList<>();
        MediaKmLitros2Classe mediaKmLitros2 = new MediaKmLitros2Classe(jTF_kilometragemInicial.getText(), jTF_litrosAbastecidos1.getText(), jTF_kilometragemFinal.getText());
        principalJFrame.usuario.getMediaKmsArray().add(mediaKmLitros2);
        
    }//GEN-LAST:event_jB_voltarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_calcular;
    private javax.swing.JButton jB_limpar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JLabel jL_kilometragemFinal;
    private javax.swing.JLabel jL_kilometragemInicial;
    private javax.swing.JLabel jL_tituloLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_kilometragemFinal;
    private javax.swing.JTextField jTF_kilometragemInicial;
    private javax.swing.JTextField jTF_litrosAbastecidos1;
    // End of variables declaration//GEN-END:variables
}
