
import Clases.Audios.AudioErro;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author nicka
 */
public class PainelMediaKmsLitro extends javax.swing.JPanel {

    /**
     * Creates new form PainelMediaKmsLitro
     */
    public PainelMediaKmsLitro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tituloLogin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jL_valorCombustivel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_kmsRodados = new javax.swing.JTextField();
        jTF_litrosAbastecidos = new javax.swing.JTextField();
        jB_calcular = new javax.swing.JButton();
        jB_limpar = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(179, 200, 144));

        jL_tituloLogin.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin.setText("Consult Trip");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jL_valorCombustivel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jL_valorCombustivel.setForeground(new java.awt.Color(255, 255, 255));
        jL_valorCombustivel.setText("Km's rodados:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Litros abastecidos:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html> Obs: insira no primeiro campo \"Km's rodados:\" a quantidade de <br> km's percorridos. No Segundo campo \"Litros abastecidos\" <br> digite a quantidade abastecida para obter a média de consumo <br> do seu veiculo! </html>");

        jB_calcular.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jB_calcular.setForeground(new java.awt.Color(109, 135, 116));
        jB_calcular.setText("Calcular");
        jB_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_calcularMouseClicked(evt);
            }
        });

        jB_limpar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_limpar.setForeground(new java.awt.Color(109, 135, 116));
        jB_limpar.setText("Limpar");
        jB_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_limparMouseClicked(evt);
            }
        });

        jB_voltar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_voltar.setForeground(new java.awt.Color(109, 135, 116));
        jB_voltar.setText("Voltar");
        jB_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_tituloLogin)
                .addGap(71, 201, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_valorCombustivel))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTF_litrosAbastecidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_kmsRodados, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jB_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_limpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jB_voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_tituloLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_valorCombustivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTF_kmsRodados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_litrosAbastecidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_voltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_calcularMouseClicked
        if (jTF_litrosAbastecidos.getText().equals("") || jTF_kmsRodados.getText().equals("")) {
            //Som de erro!
            AudioErro audioErro = new AudioErro();
            audioErro.AudioErro();
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else{
            float media;
            media = Float.parseFloat(jTF_kmsRodados.getText()) / Float.parseFloat(jTF_litrosAbastecidos.getText());
            if (media == 1) {
                // Carregar a imagem desejada
                ImageIcon icon = new ImageIcon("src/Imagens/icons8-gasolina-50.png");
                // Exibir o JOptionPane com a imagem
                JOptionPane.showMessageDialog(null, "O seu veiculo está fazendo " + media + "Km por litro de combustível!", "Sua média de Km's por litro é:", JOptionPane.INFORMATION_MESSAGE, icon);
            }else {
                // Carregar a imagem desejada
                ImageIcon icon = new ImageIcon("src/Imagens/icons8-gasolina-50.png");
                // Exibir o JOptionPane com a imagem
                JOptionPane.showMessageDialog(null, "O seu veiculo está fazendo " + media + "Km's por litros de combustível!", "Sua média de Km's por litro é:", JOptionPane.INFORMATION_MESSAGE, icon);
            }
        }
    }//GEN-LAST:event_jB_calcularMouseClicked

    private void jB_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_limparMouseClicked
        jTF_kmsRodados.setText("");
        jTF_litrosAbastecidos.setText("");
    }//GEN-LAST:event_jB_limparMouseClicked

    private void jB_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarMouseClicked
        principalJFrame.painel3 = new PainelCliente();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(principalJFrame.painel4);
        janela.add(principalJFrame.painel3, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jB_voltarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_calcular;
    private javax.swing.JButton jB_limpar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JLabel jL_tituloLogin;
    private javax.swing.JLabel jL_valorCombustivel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_kmsRodados;
    private javax.swing.JTextField jTF_litrosAbastecidos;
    // End of variables declaration//GEN-END:variables
}
