

import Clases.Audios.AudioErro;
import Clases.DespesasMultasClasse;
import Clases.Empacotamento;
import Clases.Veiculo;
import java.awt.BorderLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;



/**
 *
 * @author nicka
 */
public class PainelDespesasMultas extends javax.swing.JPanel {
    
    //ArrayList<DespesasMultasClasse> despesasArray = new ArrayList<>();
    /**
     * Creates new form PainelDespesasMultas
     */
    public PainelDespesasMultas() {
        initComponents();
        deserealizar();
        jPanel2.setVisible(false);
        preencherTabela();
        
        
    }
    String nomeDoArquivo = "teste.ser";
    DespesasMultasClasse objetoRecuperado = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tituloLogin3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jL_tituloLogin4 = new javax.swing.JLabel();
        jL_valorCombustivel2 = new javax.swing.JLabel();
        jCB_tipo = new javax.swing.JComboBox<>();
        jL_valorCombustivel1 = new javax.swing.JLabel();
        jL_valorCombustivel3 = new javax.swing.JLabel();
        jFTF_data = new javax.swing.JFormattedTextField();
        jB_voltar = new javax.swing.JButton();
        jB_historico = new javax.swing.JButton();
        jB_salvar = new javax.swing.JButton();
        jB_limpar = new javax.swing.JButton();
        jTF_valor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jL_tituloLogin5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_historico = new javax.swing.JTable();
        jB_voltar1 = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jB_excluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(179, 200, 144));
        setMaximumSize(new java.awt.Dimension(420, 270));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(472, 260));

        jL_tituloLogin3.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin3.setText("Consult Trip");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(179, 200, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 207));

        jL_tituloLogin4.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin4.setForeground(java.awt.Color.white);
        jL_tituloLogin4.setText("Pedagios, multas, despesas");

        jL_valorCombustivel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jL_valorCombustivel2.setForeground(new java.awt.Color(255, 255, 255));
        jL_valorCombustivel2.setText("Tipo:");

        jCB_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Pedagio", "Multa", "Patio", "IPVA" }));

        jL_valorCombustivel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jL_valorCombustivel1.setForeground(new java.awt.Color(255, 255, 255));
        jL_valorCombustivel1.setText("Valor:");

        jL_valorCombustivel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jL_valorCombustivel3.setForeground(new java.awt.Color(255, 255, 255));
        jL_valorCombustivel3.setText("Data:");

        try {
            jFTF_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTF_data.setText("__/__/__");
        jFTF_data.setToolTipText("<html>Digite somente os numeros,<br> sem usar \".\" ou \",\"<html>");
        jFTF_data.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jB_voltar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_voltar.setForeground(new java.awt.Color(109, 135, 116));
        jB_voltar.setText("Voltar");
        jB_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarMouseClicked(evt);
            }
        });

        jB_historico.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_historico.setForeground(new java.awt.Color(109, 135, 116));
        jB_historico.setText("<html>Historico<html>");
        jB_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_historicoMouseClicked(evt);
            }
        });

        jB_salvar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jB_salvar.setForeground(new java.awt.Color(109, 135, 116));
        jB_salvar.setText("Salvar");
        jB_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_salvarMouseClicked(evt);
            }
        });

        jB_limpar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jB_limpar.setForeground(new java.awt.Color(109, 135, 116));
        jB_limpar.setText("Limpar");
        jB_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_limparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_tituloLogin4, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_valorCombustivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_valorCombustivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_valorCombustivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTF_data))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jL_tituloLogin4)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_valorCombustivel1)
                    .addComponent(jL_valorCombustivel2)
                    .addComponent(jL_valorCombustivel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTF_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_historico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_voltar)
                    .addComponent(jB_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(179, 200, 144));
        jPanel2.setPreferredSize(new java.awt.Dimension(451, 207));

        jL_tituloLogin5.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin5.setForeground(java.awt.Color.white);
        jL_tituloLogin5.setText("Historico");

        jTable_historico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_historico.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_historico);
        if (jTable_historico.getColumnModel().getColumnCount() > 0) {
            jTable_historico.getColumnModel().getColumn(0).setResizable(false);
            jTable_historico.getColumnModel().getColumn(1).setResizable(false);
            jTable_historico.getColumnModel().getColumn(2).setResizable(false);
        }

        jB_voltar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_voltar1.setForeground(new java.awt.Color(109, 135, 116));
        jB_voltar1.setText("Voltar");
        jB_voltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltar1MouseClicked(evt);
            }
        });

        jB_editar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_editar.setForeground(new java.awt.Color(109, 135, 116));
        jB_editar.setText("Editar");
        jB_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_editarMouseClicked(evt);
            }
        });

        jB_excluir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_excluir.setForeground(new java.awt.Color(109, 135, 116));
        jB_excluir.setText("Excluir");
        jB_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_excluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jL_tituloLogin5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(306, 306, 306))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jB_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jL_tituloLogin5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_voltar1)
                    .addComponent(jB_editar)
                    .addComponent(jB_excluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jL_tituloLogin3)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jL_tituloLogin3)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void deserealizar(){
       try {
            
            FileInputStream arquivo = new FileInputStream(nomeDoArquivo);
            ObjectInputStream in = new ObjectInputStream(arquivo);
            
            
            objetoRecuperado = (DespesasMultasClasse)in.readObject();
            in.close();
            arquivo.close();
            
            System.out.println("desserializado com sucesso!");
        } catch (IOException e) {
            System.out.println("Erro de leitura do arquivo ou falha de entrada/saída.");
        }
        catch(ClassNotFoundException e){
            System.out.println("Classe não encontrada!");
        } 
    }
    
    
    private void jB_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_salvarMouseClicked
        //Empacotamento.gravarArquivoBinario(despesasArray, "Despesas.ser");
        if (jTF_valor.getText().equals("") || jFTF_data.getText().equals("") || jCB_tipo.getSelectedIndex() == 0){
            //Som de erro!
                AudioErro audioErro = new AudioErro();
                audioErro.AudioErro();
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else {
            //Adicionar
            DespesasMultasClasse despesas = new DespesasMultasClasse((String) jCB_tipo.getSelectedItem(), jTF_valor.getText(), jFTF_data.getText());
            principalJFrame.usuario.getDespesas().add(despesas);
            //despesasArray.add(despesas);
            System.out.println(jCB_tipo.getSelectedItem());
            //
            //Limpar campos
            jTF_valor.setText("");
            jFTF_data.setText("");
            jCB_tipo.setSelectedIndex(0);
            preencherTabela();
            JOptionPane.showMessageDialog(null, "Os dados inseridos foram salvos!");
            
            try{//Serrealização
                FileOutputStream arquivo = new FileOutputStream(nomeDoArquivo);
                ObjectOutputStream out = new ObjectOutputStream(arquivo);

                out.writeObject(despesas);
                out.close();
                arquivo.close();
                System.out.println("foi serealizado!");
            } catch (IOException e) {
                System.out.println("ERRO na serealização");
            }
        }
    }//GEN-LAST:event_jB_salvarMouseClicked
    
    DefaultTableModel modeloTabela = new DefaultTableModel();
    public void preencherTabela(){
        
        int n = principalJFrame.usuario.getDespesas().size();
        System.out.println(n);
        String colunas[] = {"Tipo", "Valor", "Data"};
        String linhas[][] = new String[n][3];
        int j = 0;
        
        for (int i = 0; i < n; i++) {
            linhas[i][j] = principalJFrame.usuario.getDespesas().get(i).getTipo();
            j++;
            linhas[i][j] = principalJFrame.usuario.getDespesas().get(i).getValor();
            j++;
            linhas[i][j] = principalJFrame.usuario.getDespesas().get(i).getData();
            j=0;
        }
        this.modeloTabela = new DefaultTableModel(linhas, colunas){
            public boolean isCellEditable(int rowIndex, int mColIndex){
                return false;
            }
        };
        jTable_historico.setModel(modeloTabela);       
    }
    
    private void jB_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarMouseClicked
        principalJFrame.painel3 = new PainelCliente();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(principalJFrame.painel11);
        janela.add(principalJFrame.painel3, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jB_voltarMouseClicked

    private void jB_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_historicoMouseClicked
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jB_historicoMouseClicked

    private void jB_voltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltar1MouseClicked
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jB_voltar1MouseClicked

    private void jB_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_limparMouseClicked
        jCB_tipo.setSelectedIndex(0);
        jTF_valor.setText("");
        jFTF_data.setText("");
    }//GEN-LAST:event_jB_limparMouseClicked

    private void jB_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_editarMouseClicked
        //obter qual a celula foi selecionada
        int selectedRow = jTable_historico.getSelectedRow();

        if (selectedRow >= 0) {
            // Aparecer o painel
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);

            // Obter os valores dos produtos que serão editados
            int contadorLinha = 0; // Contador para rastrear o índice da linha atual

            for (DespesasMultasClasse despesa : principalJFrame.usuario.getDespesas()) {
                if (contadorLinha == selectedRow) {
                    jTF_valor.setText(despesa.getValor());
                    jFTF_data.setText(despesa.getData());
                    jCB_tipo.setSelectedItem(despesa.getTipo());

                    // Remover
                    ((DefaultTableModel) jTable_historico.getModel()).removeRow(selectedRow);
                    System.out.println("Despesa removida!");

                    // Remover a despesa do ArrayList
                    principalJFrame.usuario.getDespesas().remove(despesa);
                    break;
                }

                contadorLinha++; // adiciona no contador de linha
            }
        } else {
            System.out.println("Nenhuma célula selecionada.");
            JOptionPane.showMessageDialog(null, "Nenhuma célula selecionada.");
            
        }
        
        
    }//GEN-LAST:event_jB_editarMouseClicked

    private void jB_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_excluirMouseClicked
        removerSelecionadoTabela();
    }//GEN-LAST:event_jB_excluirMouseClicked
    
    public void removerSelecionadoTabela() {
        int selectedRow = jTable_historico.getSelectedRow();

        if (selectedRow >= 0) {
            ((DefaultTableModel) jTable_historico.getModel()).removeRow(selectedRow);
            System.out.println("Veículo removida com sucesso!");
            JOptionPane.showMessageDialog(null, "Veículo removida com sucesso!");
            // Remove o veículo do ArrayList
            principalJFrame.usuario.getDespesas().remove(selectedRow);
        } else {
            System.out.println("Nenhuma celula selecionada.");
            JOptionPane.showMessageDialog(null, "Nenhuma celula selecionada.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_excluir;
    private javax.swing.JButton jB_historico;
    private javax.swing.JButton jB_limpar;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JButton jB_voltar1;
    private javax.swing.JComboBox<String> jCB_tipo;
    private javax.swing.JFormattedTextField jFTF_data;
    private javax.swing.JLabel jL_tituloLogin3;
    private javax.swing.JLabel jL_tituloLogin4;
    private javax.swing.JLabel jL_tituloLogin5;
    private javax.swing.JLabel jL_valorCombustivel1;
    private javax.swing.JLabel jL_valorCombustivel2;
    private javax.swing.JLabel jL_valorCombustivel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTF_valor;
    private javax.swing.JTable jTable_historico;
    // End of variables declaration//GEN-END:variables
}
