import Clases.Veiculo;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author alunolages
 */
public class SuaGaragem extends javax.swing.JPanel {

    /**
     * Creates new form SuaGaragem
     */
    public SuaGaragem() {
        initComponents();
        preencherTabela();
    }
    
    
    DefaultTableModel modeloTabela = new DefaultTableModel();
    public void preencherTabela(){
        for(Veiculo veiculo : principalJFrame.usuario.getVeiculosArray()){
            System.out.println(veiculo.getKilometragem());
        }
        int n = principalJFrame.usuario.getVeiculosArray().size();
        System.out.println(n);
        String colunas[] = {"Marca", "Modelo", "Ano", "Motorizacao", "Cor", "Placa", "Tipo"};
        String linhas[][] = new String[n][7];
        
        
        for (int i = 0; i < n; i++) {
            int j = 0;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getMarcaDoVeiculo();
            j++;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getModelo();
            j++;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getAno();
            j++;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getCor();
            j++;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getMotorizacao();
            j++;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getPlaca();
            j++;
            linhas[i][j] = principalJFrame.usuario.getVeiculosArray().get(i).getTipoDoVeiculo();
            j++;
        }
        this.modeloTabela = new DefaultTableModel(linhas, colunas){
            public boolean isCellEditable(int rowIndex, int mColIndex){
                return false;
            }
        };
        jTable_garagem.setModel(modeloTabela);       
    }
    
    public void removerSelecionadoTabela() {
        int selectedRow = jTable_garagem.getSelectedRow();

        if (selectedRow >= 0) {
            ((DefaultTableModel) jTable_garagem.getModel()).removeRow(selectedRow);
            System.out.println("Veículo removida com sucesso!");
            JOptionPane.showMessageDialog(null, "Veículo removida com sucesso!");
            // Remove o veículo do ArrayList
            principalJFrame.usuario.getVeiculosArray().remove(selectedRow);
        } else {
            System.out.println("Nenhum veiculo selecionado.");
            JOptionPane.showMessageDialog(null, "Nenhum veiculo selecionado.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tituloLogin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jB_cadastrarMaisVeiculo = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();
        jB_removerDaGaragem = new javax.swing.JButton();
        jL_tituloLogin1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_garagem = new javax.swing.JTable();

        setBackground(new java.awt.Color(179, 200, 144));

        jL_tituloLogin.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin.setText("Consult Trip");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jB_cadastrarMaisVeiculo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jB_cadastrarMaisVeiculo.setForeground(new java.awt.Color(109, 135, 116));
        jB_cadastrarMaisVeiculo.setText("Cadastrar um veiculo");
        jB_cadastrarMaisVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_cadastrarMaisVeiculoMouseClicked(evt);
            }
        });

        jB_voltar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_voltar.setForeground(new java.awt.Color(109, 135, 116));
        jB_voltar.setText("Voltar");
        jB_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_voltarMouseClicked(evt);
            }
        });

        jB_removerDaGaragem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jB_removerDaGaragem.setForeground(new java.awt.Color(109, 135, 116));
        jB_removerDaGaragem.setText("<html>Remover da garagem<html>");
        jB_removerDaGaragem.setBorder(null);
        jB_removerDaGaragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_removerDaGaragemMouseClicked(evt);
            }
        });

        jL_tituloLogin1.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        jL_tituloLogin1.setForeground(java.awt.Color.white);
        jL_tituloLogin1.setText("Sua garagem:");

        jTable_garagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Ano", "Cor", "Motorização", "Placa", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_garagem);
        if (jTable_garagem.getColumnModel().getColumnCount() > 0) {
            jTable_garagem.getColumnModel().getColumn(0).setResizable(false);
            jTable_garagem.getColumnModel().getColumn(1).setResizable(false);
            jTable_garagem.getColumnModel().getColumn(2).setResizable(false);
            jTable_garagem.getColumnModel().getColumn(3).setResizable(false);
            jTable_garagem.getColumnModel().getColumn(4).setResizable(false);
            jTable_garagem.getColumnModel().getColumn(5).setResizable(false);
            jTable_garagem.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_tituloLogin1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_cadastrarMaisVeiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jB_removerDaGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jL_tituloLogin)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jL_tituloLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_cadastrarMaisVeiculo)
                            .addComponent(jB_voltar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jB_removerDaGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jL_tituloLogin)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(357, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_voltarMouseClicked
        principalJFrame.painel3 = new PainelCliente();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(principalJFrame.painel10);
        janela.add(principalJFrame.painel3, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jB_voltarMouseClicked

    private void jB_removerDaGaragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_removerDaGaragemMouseClicked
        removerSelecionadoTabela();
    }//GEN-LAST:event_jB_removerDaGaragemMouseClicked

    private void jB_cadastrarMaisVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_cadastrarMaisVeiculoMouseClicked
        principalJFrame.painel9 = new PainelDadosVeiculo();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(principalJFrame.painel10);
        janela.add(principalJFrame.painel9, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jB_cadastrarMaisVeiculoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cadastrarMaisVeiculo;
    private javax.swing.JButton jB_removerDaGaragem;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JLabel jL_tituloLogin;
    private javax.swing.JLabel jL_tituloLogin1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_garagem;
    // End of variables declaration//GEN-END:variables
}
